services:
  # MariaDB (Database)
  mariadb:
    build: ./database
    container_name: mariadb
    restart: always
    env_file: .env
    ports:
      - "${MARIADB_PORT:-3306}:3306"
    volumes:
      # Logs and config
      - ./database/logs:/var/log/mysql
      - ./database/my.cnf:/etc/mysql/conf.d/my.cnf
      # Persistant volumes
      - ./database/data:/var/lib/mysql
    networks:
      - app_network

  # phpMyAdmin
  phpmyadmin:
    image: phpmyadmin:5.2.1
    container_name: phpmyadmin
    restart: always
    depends_on:
      - mariadb
    environment:
      PMA_HOST: mariadb
      PMA_PORT: 3306
      PMA_USER: ${MARIADB_USER}
      PMA_PASSWORD: ${MARIADB_PASSWORD}

    volumes:
      - "./php.ini:/usr/local/etc/php/conf.d/custom.ini"
    ports:
      - "${PHPMYADMIN_PORT:-8081}:80"
    networks:
      - app_network

  # Bike
  bike:
    container_name: bike
    build:
      context: ./bike
      dockerfile: Dockerfile
    restart: always
    env_file: .env
    depends_on:
      - api
    volumes:
      - ./bike:/app
      - /app/node_modules
    command: npx nodemon index.mjs
    ports:
      - "${BIKE_PORT:-7071}:7071"
    networks:
      - app_network

  # API
  api:
    container_name: api
    build:
      context: ./api
      dockerfile: Dockerfile
    restart: always
    env_file: .env
    depends_on:
      - mariadb
    volumes:
      - ./api:/app
      - /app/node_modules
    command: npx nodemon index.mjs
    ports:
      - "${API_PORT:-9091}:9091" # Expose to host for testing
    networks:
      - app_network

  client:
    container_name: client
    build:
      context: ./client
      dockerfile: Dockerfile
      restart: always
      env_file: .env
      depends_on:
        - api
      ports:
        - "${USER_CLIENT_PORT:5174}:5174"
      networks:
        - app_network

  # ADMIN CLIENT
  admin-client:
    container_name: admin-client
    build:
      context: ./admin-client
      dockerfile: Dockerfile
    restart: always
    env_file: .env
    depends_on:
       - api
    volumes:
      - ./admin-client:/app
      - /app/node_modules
    command: npm run dev
    ports:
      - "${ADMIN_CLIENT_PORT:-5173}:5173" # Expose to host for testing
    networks:
       - app_network

networks:
  app_network:
    driver: bridge
